# Generated by Django 4.2.14 on 2024-07-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitySearchCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, unique=True)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="city",
            field=models.CharField(max_length=100),
        ),
    ]
